name: HTML Code Checks

on:
  push:
    branches:
      - main

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install HTML linter
      run: npm install -g html-validate
      
    - name: Validate HTML files
      run: html-validate --format=stylish .
